### ISSUE TITLE
Support for GTFS-R realtime version 2

### ISSUE THREAD

**Issue by ashif-ismail** [OneBusAway/onebusaway-gtfs-realtime-exporter#12]
Kindly please provide the option to use GTFS-R binding version 2, seems google is needing this now.

**Comment by barbeau** [comment]
@SheikhZayed I believe that support should exist now - you just need to set the version to "2.0" when publishing the feed. v2 of GTFS-RT is a semantic version, not a hard version number in the library. See https://barbeau.medium.com/whats-new-in-gtfs-realtime-v2-0-cd45e6a861e9 for details.
